INSERT INTO category (category_name) VALUES ('French');
INSERT INTO category (category_name) VALUES ('Japanese');
INSERT INTO category (category_name) VALUES ('Italian');
INSERT INTO category (category_name) VALUES ('Indian');
INSERT INTO unit_of_measurement (unit_of_measurement) VALUES ('tsp');
INSERT INTO unit_of_measurement (unit_of_measurement) VALUES ('tbsp');
INSERT INTO unit_of_measurement (unit_of_measurement) VALUES ('cup');
INSERT INTO unit_of_measurement (unit_of_measurement) VALUES ('pinch');
INSERT INTO unit_of_measurement (unit_of_measurement) VALUES ('grams');